log = __builtins__["log"]
colorLog = __builtins__["colorLog"]
fastLog = __builtins__["fastLog"]
setTimeout = __builtins__["setTimeout"]
setInterval = __builtins__["setInterval"]
clearInterval = __builtins__["clearInterval"]
handle = __builtins__["handle"]
