from typing import NoReturn

from ..pointer import NativePointer

class GlobalPointer:
    """全局指针 API"""

    def __init__(self) -> NoReturn: ...
    @staticmethod
    def Level() -> NativePointer: ...
    @staticmethod
    def Minecraft() -> NativePointer: ...
    @staticmethod
    def ServerNetworkHandler() -> NativePointer: ...
    @staticmethod
    def MinecraftCommands() -> NativePointer: ...
    @staticmethod
    def LevelStorage() -> NativePointer: ...
    @staticmethod
    def DBStorage() -> NativePointer: ...
    @staticmethod
    def RakNetServerLocator() -> NativePointer: ...
    @staticmethod
    def RakNetRakPeer() -> NativePointer: ...
    @staticmethod
    def Scoreboard() -> NativePointer: ...
    @staticmethod
    def AllowListFile() -> NativePointer: ...
    @staticmethod
    def PropertiesSettings() -> NativePointer: ...
